### ISSUE TITLE
Remove number validation for salesPrice at Edit Product API

### ISSUE THREAD

**Issue by wasddsaw** [unit-6/101-backend#14]
### Description
`salesPrice` parameter at edit product API state String

Request

<img width="493" alt="Screenshot 2021-06-02 at 6 44 24 PM" src="https://user-images.githubusercontent.com/23319632/120467247-8feaa480-c3d2-11eb-86fe-677625cc5722.png">

Response

<img width="1253" alt="Screenshot 2021-06-02 at 6 40 05 PM" src="https://user-images.githubusercontent.com/23319632/120467200-7ea19800-c3d2-11eb-9c85-c8de098525c5.png">

### Proposal
Remove number validation for `salesPrice` parameter

**Comment by miesaf** [comment]
salesPrice should not include 'RM' since it's a numeric fields and not string
